### ISSUE TITLE
new features

### ISSUE THREAD

**Issue by megoRU** [WardPearce/SM-Map-Statistics#1]
![image](https://user-images.githubusercontent.com/23276305/54643619-6cb0d480-4aa8-11e9-82d5-78e6fe95eaa7.png)

By the way, I translated into Russian. if necessary I can drop the file

@The-Doggy 
@WardPearce

**Comment by WardPearce** [comment]
Yea, that would be great :)
I'm planning to update the web script soonish once I've got some more private work done.

**Comment by megoRU** [comment]
90% translated into Russian.

[index.zip](https://github.com/DistrictNineHost/SM-Map-Statistics/files/2987854/index.zip)

**Comment by megoRU** [comment]
@WardPearce 
I'm sorry I messed up something there ...
remove my
https://github.com/DistrictNineHost/SM-Map-Statistics/pulls
